/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

/**
 *
 * @author sajid
 */
public class AdminChoice extends javax.swing.JFrame {

    /**
     * Creates new form AdminChoice
     */
    public AdminChoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentjButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        backjButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("      Select Your Choice");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(81, 22, 359, 69);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel2.setText("   Which  part  do you  want  to  manipulate --");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(32, 97, 438, 41);

        studentjButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        studentjButton1.setText("STUDENTS' PART");
        studentjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(studentjButton1);
        studentjButton1.setBounds(140, 150, 220, 58);

        jButton2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton2.setText("TEACHERS' PART");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 230, 220, 62);

        backjButton3.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        backjButton3.setText("BACK");
        backjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(backjButton3);
        backjButton3.setBounds(360, 300, 110, 41);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/light-blue-background-3.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 480, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton3ActionPerformed
        this.setVisible(false);
        Admin_info ad = new Admin_info();
        ad.setVisible(true);
        ad.setBounds(0, 0, 487, 380);
        
    }//GEN-LAST:event_backjButton3ActionPerformed

    private void studentjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentjButton1ActionPerformed
        this.setVisible(false);
        St_Information st = new St_Information();
        st.setVisible(true);
        st.setBounds(0, 0, 1213, 900);
        st.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_studentjButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        Teacher_Information teacher = new Teacher_Information();
        teacher.setVisible(true);
        teacher.setBounds(0, 0, 1210, 730);
        teacher.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton studentjButton1;
    // End of variables declaration//GEN-END:variables
}
