/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sajid
 */
public class St_Information extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form St_Information
     */
    public St_Information() {
        initComponents();
        retrieve();
    }

    public void retrieve() {
        DefaultTableModel dm = getData();
        jTable1.setModel(dm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        user_txt = new javax.swing.JTextField();
        Pass_txt = new javax.swing.JTextField();
        DOB_txt = new javax.swing.JTextField();
        Email_txt = new javax.swing.JTextField();
        Atndnc_txt = new javax.swing.JTextField();
        ST_name = new javax.swing.JTextField();
        ST_ID = new javax.swing.JTextField();
        ST_dept = new javax.swing.JTextField();
        ST_cg = new javax.swing.JTextField();
        ST_cell = new javax.swing.JTextField();
        addjButton1 = new javax.swing.JButton();
        retrievejButton2 = new javax.swing.JButton();
        updatejButton3 = new javax.swing.JButton();
        deletejButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        clearjButton1 = new javax.swing.JButton();
        signoutjButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setText("     STUDENTS'  INFORMATION");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setText("    STUDENT NAME");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setText("    STUDENT ID");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel4.setText("    DEPARTMENT");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel5.setText("    CGPA");

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel6.setText("    CELL NO.");

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel7.setText("    USER NAME");

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel8.setText("    PASSWORD");

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel9.setText("    DATE OF BIRTH");

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel10.setText("    E-MAIL");

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel11.setText("    ATTENDANCE");

        addjButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        addjButton1.setText("ADD INFO");
        addjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton1ActionPerformed(evt);
            }
        });

        retrievejButton2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        retrievejButton2.setText("RETRIEVE");
        retrievejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrievejButton2ActionPerformed(evt);
            }
        });

        updatejButton3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        updatejButton3.setText("UPDATE");
        updatejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton3ActionPerformed(evt);
            }
        });

        deletejButton4.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        deletejButton4.setText("DELETE");
        deletejButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Department", "CGPA", "Cell no.", "User name", "Password", "DOB", "E-mail", "Attendance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        clearjButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        clearjButton1.setText("CLEAR");
        clearjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearjButton1ActionPerformed(evt);
            }
        });

        signoutjButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        signoutjButton1.setText("SIGN OUT");
        signoutjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ST_name)
                                    .addComponent(ST_ID)
                                    .addComponent(ST_dept)
                                    .addComponent(ST_cell)
                                    .addComponent(ST_cg, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(220, 220, 220)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(user_txt)
                                    .addComponent(Pass_txt)
                                    .addComponent(DOB_txt)
                                    .addComponent(Email_txt)
                                    .addComponent(Atndnc_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(260, 260, 260)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(signoutjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(retrievejButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatejButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletejButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(user_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ST_name, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(103, 103, 103))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(DOB_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ST_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ST_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ST_cg, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Atndnc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ST_cell, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(signoutjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(addjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(retrievejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updatejButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletejButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public DefaultTableModel getData() {
        //ADD COLUMNS TO TABLE MODEL
        
        DefaultTableModel dm = new DefaultTableModel();
        dm.addColumn("id");
        dm.addColumn("name");
        dm.addColumn("department");
        dm.addColumn("cgpa");
        dm.addColumn("cellno");
        dm.addColumn("username");
        dm.addColumn("password");
        dm.addColumn("dob");
        dm.addColumn("email");
        dm.addColumn("attendance");

        //SQL STATEMENT
        String sql = "SELECT * FROM student";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management", "root", "");
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);

            //LOOP THROUGH ALL VALUES
            while (rs.next()) {
                //GET VALUES
                String id = rs.getString(1);
                String name = rs.getString(2);           
                String department = rs.getString(3);
                String cgpa = rs.getString(4);
                String cellno = rs.getString(5);
                String username = rs.getString(6);
                String password = rs.getString(7);
                String dob = rs.getString(8);
                String email = rs.getString(9);
                String attendance = rs.getString(10);

                dm.addRow(new String[]{id, name, department, cgpa, cellno, username, password, dob, email, attendance});
            }
            return dm;

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }


    private void addjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton1ActionPerformed

        String sql = "Insert into student(id, name, department,cgpa, cellno,username,password,dob,email,attendance) values(?,?,?,?,?,?,?,?,?,?)";

        
        if(ST_name.getText().equalsIgnoreCase("")||ST_ID.getText().equalsIgnoreCase("")||Atndnc_txt.getText().equalsIgnoreCase("")||ST_dept.getText().equalsIgnoreCase("")||ST_cg.getText().equalsIgnoreCase("")||ST_cell.getText().equalsIgnoreCase("")||user_txt.getText().equalsIgnoreCase("")||Pass_txt.getText().equalsIgnoreCase("")||DOB_txt.getText().equalsIgnoreCase("")||Email_txt.getText().equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(null, "You must fill up the above boxes correcrtly");
            }
        else{
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management", "root", "");
            pst = (PreparedStatement) conn.prepareStatement(sql);

            pst.setInt(1, Integer.parseInt(ST_ID.getText().trim()));
            pst.setString(2, ST_name.getText().trim());
            pst.setString(3, ST_dept.getText().trim());
            pst.setFloat(4, Float.parseFloat(ST_cg.getText().trim()));
            pst.setString(5, ST_cell.getText().trim());
            pst.setString(6, user_txt.getText().trim());
            pst.setString(7, Pass_txt.getText().trim());
            pst.setString(8, DOB_txt.getText().trim());
            pst.setString(9, Email_txt.getText().trim());
            pst.setInt(10, Integer.parseInt(Atndnc_txt.getText().trim()));
            
            int v = pst.executeUpdate();

            if (v == 1) {
                JOptionPane.showMessageDialog(null, "Successfully Inserted");
                retrieve();
            }
                        
            else {
                JOptionPane.showMessageDialog(null, "Successfully Not Inserted");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        }

    }//GEN-LAST:event_addjButton1ActionPerformed

    private void updatejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton3ActionPerformed

        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management", "root", "");

            String value1 = ST_ID.getText();
            String value2 = ST_name.getText();
            String value3 = ST_dept.getText();
            String value4 = ST_cg.getText();
            String value5 = ST_cell.getText();
            String value6 = user_txt.getText();
            String value7 = Pass_txt.getText();
            String value8 = DOB_txt.getText();
            String value9 = Email_txt.getText();
            String value10 = Atndnc_txt.getText();

            String sql = "UPDATE `student` SET `name`='" + value2 + "',`department`='" + value3 + "',`cgpa`='" + value4 + "',`cellno`='" + value5 + "',`username`='" + value6 + "',`password`='" + value7 + "',`dob`='" + value8 + "',`email`='" + value9 + "',`attendance`='" + value10 + "' WHERE `id`='" + value1 + "'";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully Updated");
        } catch (Exception e) {
            e.printStackTrace();
        }

        retrieve();
    }//GEN-LAST:event_updatejButton3ActionPerformed

    //SET seleccted values to the text fields 
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        ST_ID.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        String name = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        ST_name.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        String department = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        ST_dept.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        String cgpa = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        ST_cg.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        String cellno = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        ST_cell.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        String username = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
        user_txt.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        String password = jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
        Pass_txt.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        String dob = jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString();
        DOB_txt.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        String email = jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString();
        Email_txt.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
        String attendance = jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString();
        Atndnc_txt.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void clearjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearjButton1ActionPerformed

        ST_ID.setText("");
        ST_name.setText("");
        ST_dept.setText("");
        ST_cg.setText("");
        ST_cell.setText("");
        user_txt.setText("");
        Pass_txt.setText("");
        DOB_txt.setText("");
        Email_txt.setText("");
        Atndnc_txt.setText("");

    }//GEN-LAST:event_clearjButton1ActionPerformed

    private void deletejButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButton4ActionPerformed

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management", "root", "");

            String value1 = ST_ID.getText();
            String value2 = ST_name.getText();
            String value3 = ST_dept.getText();
            String value4 = ST_cg.getText();
            String value5 = ST_cell.getText();
            String value6 = user_txt.getText();
            String value7 = Pass_txt.getText();
            String value8 = DOB_txt.getText();
            String value9 = Email_txt.getText();
            String value10 = Atndnc_txt.getText();

            String sql = "delete from student  where id ='" + value1 + "'";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully Deleted");
        } catch (Exception e) {
            e.printStackTrace();
        }

        retrieve();
    }//GEN-LAST:event_deletejButton4ActionPerformed

    private void retrievejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrievejButton2ActionPerformed

        retrieve();
    }//GEN-LAST:event_retrievejButton2ActionPerformed

    private void signoutjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutjButton1ActionPerformed

        
        int result = JOptionPane.showConfirmDialog(null,
        "Are you sure you wish to exit application?", null, JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        Admin_info ad = new Admin_info();
        ad.setVisible(true);
        ad.setBounds(0, 0, 718, 435);
        ad.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
        
    }//GEN-LAST:event_signoutjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(St_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(St_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(St_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(St_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new St_Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Atndnc_txt;
    private javax.swing.JTextField DOB_txt;
    private javax.swing.JTextField Email_txt;
    private javax.swing.JTextField Pass_txt;
    private javax.swing.JTextField ST_ID;
    private javax.swing.JTextField ST_cell;
    private javax.swing.JTextField ST_cg;
    private javax.swing.JTextField ST_dept;
    private javax.swing.JTextField ST_name;
    private javax.swing.JButton addjButton1;
    private javax.swing.JButton clearjButton1;
    private javax.swing.JButton deletejButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton retrievejButton2;
    private javax.swing.JButton signoutjButton1;
    private javax.swing.JButton updatejButton3;
    private javax.swing.JTextField user_txt;
    // End of variables declaration//GEN-END:variables
}
