/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author sajid
 */
public class Startpage1 extends javax.swing.JFrame {

    /**
     * Creates new form Startpage1
     */
    public Startpage1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        teacherinfojButton1 = new javax.swing.JButton();
        studentinfojButton2 = new javax.swing.JButton();
        informationjButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        adminjButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/pro1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(771, 568));
        jLabel3.setMinimumSize(new java.awt.Dimension(771, 568));
        jLabel3.setPreferredSize(new java.awt.Dimension(806, 568));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Intellectual_Presidium");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 20, 500, 60);

        teacherinfojButton1.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        teacherinfojButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/info logo.jpg"))); // NOI18N
        teacherinfojButton1.setText("    TEACHER INFO");
        teacherinfojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherinfojButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(teacherinfojButton1);
        teacherinfojButton1.setBounds(510, 240, 220, 60);

        studentinfojButton2.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        studentinfojButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/info logo.jpg"))); // NOI18N
        studentinfojButton2.setText("    STUDENT INFO");
        studentinfojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentinfojButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(studentinfojButton2);
        studentinfojButton2.setBounds(510, 330, 220, 60);

        informationjButton3.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        informationjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/us.jpg"))); // NOI18N
        informationjButton3.setText("    ABOUT US");
        informationjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationjButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(informationjButton3);
        informationjButton3.setBounds(30, 420, 190, 70);

        jButton4.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(600, 420, 128, 70);

        adminjButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        adminjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/info logo.jpg"))); // NOI18N
        adminjButton1.setText("    ADMIN");
        adminjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(adminjButton1);
        adminjButton1.setBounds(510, 150, 220, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/isms.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 450, 300);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/deep background.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 770, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //exit ar kaj ase
        
        int result = JOptionPane.showConfirmDialog(null,
        "Are you sure you wish to exit application?", null, JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void informationjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationjButton3ActionPerformed
        //about us ar kaj ase akhne

        JOptionPane.showMessageDialog(null, "Developed by \n Syed Sajid Mahboob \n\t\t & \n Najoa Asreen Saif\n\t\t & \n Sadman Ahsan Susumoy\n AUST\n CSE 2.1");
    }//GEN-LAST:event_informationjButton3ActionPerformed

    private void studentinfojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentinfojButton2ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        STUDENT_INFO si = new STUDENT_INFO();
        si.setVisible(true);
        si.setBounds(0, 0, 680, 470);

    }//GEN-LAST:event_studentinfojButton2ActionPerformed

    private void teacherinfojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherinfojButton1ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        TEACHER_INFO ti = new TEACHER_INFO();
        ti.setVisible(true);
        ti.setBounds(0, 0, 758, 390);
        //tc.setBounds(0, 0, 470, 400);

    }//GEN-LAST:event_teacherinfojButton1ActionPerformed

    private void adminjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminjButton1ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        Admin_info ad = new Admin_info();
        ad.setVisible(true);
        ad.setBounds(0, 0, 718, 435);
    }//GEN-LAST:event_adminjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startpage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startpage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminjButton1;
    private javax.swing.JButton informationjButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton studentinfojButton2;
    private javax.swing.JButton teacherinfojButton1;
    // End of variables declaration//GEN-END:variables
}
