/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sajid
 */
public class STUDENT_INFO extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form STUDENT_INFO
     */
    public STUDENT_INFO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        student_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loginjButton1 = new javax.swing.JButton();
        backjButton2 = new javax.swing.JButton();
        student_password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        jLabel4.setBackground(new java.awt.Color(0, 0, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/light-blue-background-3.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jTextField2.setBackground(new java.awt.Color(0, 255, 102));
        jTextField2.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/light-blue-background-3.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        jPasswordField1.setBackground(new java.awt.Color(102, 255, 102));

        jTextField3.setBackground(new java.awt.Color(153, 255, 153));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("STUDENT_INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 320, 43);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("    USER NAME :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 120, 130, 34);

        student_name.setBackground(new java.awt.Color(153, 255, 255));
        student_name.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        getContentPane().add(student_name);
        student_name.setBounds(430, 110, 210, 60);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("   PASSWORD :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 230, 120, 45);

        loginjButton1.setBackground(new java.awt.Color(0, 204, 204));
        loginjButton1.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        loginjButton1.setForeground(new java.awt.Color(255, 255, 255));
        loginjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/Login-Button.jpg"))); // NOI18N
        loginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginjButton1);
        loginjButton1.setBounds(300, 360, 140, 50);

        backjButton2.setBackground(new java.awt.Color(255, 255, 255));
        backjButton2.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        backjButton2.setForeground(new java.awt.Color(255, 255, 255));
        backjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/back logo.jpg"))); // NOI18N
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(backjButton2);
        backjButton2.setBounds(500, 360, 140, 50);

        student_password.setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().add(student_password);
        student_password.setBounds(430, 220, 210, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagement/login logo.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 60, 270, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Startpage1 nj = new Startpage1();
        nj.setVisible(true);
        nj.setBounds(0, 0, 770, 568);
    }//GEN-LAST:event_backjButton2ActionPerformed

    private void loginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButton1ActionPerformed
        String sql = "Select * from student where username=? and password=?";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management", "root", "");
            pst = (PreparedStatement) conn.prepareStatement(sql);
            System.out.println("Password: " + student_name.getText());
            pst.setString(1, student_name.getText().trim());
            pst.setString(2, student_password.getText().trim());
            rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Username and Password Matched");
                 
                
                Stinfoshow si = new Stinfoshow();
                si.setVisible(true);
                this.setVisible(false);
                si.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                //si.setBounds(0, 0, 1213, 900);
            }
            
           /* else if(student_name.showText() == null || student_password.getText() == null)
            {
                JOptionPane.showMessageDialog(null, "Please insert valid information.");
            }*/
            else {
                JOptionPane.showMessageDialog(null, "Username and Password Not Matched");
                student_name.setText("");
                student_password.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loginjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STUDENT_INFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STUDENT_INFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STUDENT_INFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STUDENT_INFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STUDENT_INFO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton loginjButton1;
    public static javax.swing.JTextField student_name;
    private javax.swing.JPasswordField student_password;
    // End of variables declaration//GEN-END:variables
}
