/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sajid
 */
public class Teacher_Information extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Teacher_Information
     */
    public Teacher_Information() {
        initComponents();

        retrieve();
    }

    public void retrieve() {
        DefaultTableModel dm = getData();
        jTable1.setModel(dm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public DefaultTableModel getData() {
        //ADD COLUMNS TO TABLE MODEL

        DefaultTableModel dm = new DefaultTableModel();
        dm.addColumn("id");
        dm.addColumn("name");
        dm.addColumn("cellno");
        dm.addColumn("department");
        dm.addColumn("designation");
        dm.addColumn("email");
        dm.addColumn("username");
        dm.addColumn("password");

        //SQL STATEMENT
        String sql = "SELECT * FROM teacher";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management", "root", "");
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);

            //LOOP THROUGH ALL VALUES
            while (rs.next()) {
                //GET VALUES

                String id = rs.getString(1);
                String name = rs.getString(2);
                String username = rs.getString(3);
                String password = rs.getString(4);
                String cellno = rs.getString(5);
                String department = rs.getString(6);
                String designation = rs.getString(7);
                String email = rs.getString(8);

                dm.addRow(new String[]{id, name, cellno, department, designation, email, username, password});
            }
            return dm;

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        teacher_id = new javax.swing.JTextField();
        teacher_name = new javax.swing.JTextField();
        teacher_cell = new javax.swing.JTextField();
        teacher_dept = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        teacher_designation = new javax.swing.JTextField();
        teacher_mail = new javax.swing.JTextField();
        teacher_username = new javax.swing.JTextField();
        teacher_password = new javax.swing.JPasswordField();
        add_jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        deletejButton4 = new javax.swing.JButton();
        updatejButton5 = new javax.swing.JButton();
        clearjButton1 = new javax.swing.JButton();
        signoutjButton2 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Cellno", "Department", "Designation", "E-mail", "username", "password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jScrollPane1.setViewportView(jScrollPane2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 419, 1190, 260);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setText("     TEACHERS'  INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(384, 13, 347, 49);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setText("Teacher Id:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 69, 151, 50);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 156, 151, 54);

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel4.setText("Cell no. :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 250, 151, 57);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel5.setText("Department :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(4, 337, 151, 48);
        getContentPane().add(teacher_id);
        teacher_id.setBounds(171, 68, 236, 54);
        getContentPane().add(teacher_name);
        teacher_name.setBounds(171, 156, 236, 54);
        getContentPane().add(teacher_cell);
        teacher_cell.setBounds(171, 251, 236, 57);
        getContentPane().add(teacher_dept);
        teacher_dept.setBounds(173, 337, 234, 58);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel7.setText("Designation :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 71, 171, 51);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel8.setText("E-Mail :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(570, 163, 171, 50);

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel9.setText("Username :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(570, 231, 171, 58);

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel10.setText("Password :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(570, 319, 171, 51);
        getContentPane().add(teacher_designation);
        teacher_designation.setBounds(745, 78, 210, 44);
        getContentPane().add(teacher_mail);
        teacher_mail.setBounds(745, 156, 210, 47);
        getContentPane().add(teacher_username);
        teacher_username.setBounds(745, 243, 210, 46);
        getContentPane().add(teacher_password);
        teacher_password.setBounds(745, 320, 210, 51);

        add_jButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        add_jButton1.setText("ADD INFO");
        add_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(add_jButton1);
        add_jButton1.setBounds(980, 20, 141, 48);

        jButton3.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton3.setText("RETRIEVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(980, 80, 141, 47);

        deletejButton4.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        deletejButton4.setText("DELETE");
        deletejButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(deletejButton4);
        deletejButton4.setBounds(980, 150, 141, 46);

        updatejButton5.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        updatejButton5.setText("UPDATE");
        updatejButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(updatejButton5);
        updatejButton5.setBounds(980, 210, 141, 46);

        clearjButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        clearjButton1.setText("Clear");
        clearjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(clearjButton1);
        clearjButton1.setBounds(980, 270, 140, 50);

        signoutjButton2.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        signoutjButton2.setText("Sign Out");
        signoutjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutjButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(signoutjButton2);
        signoutjButton2.setBounds(980, 340, 140, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_jButton1ActionPerformed

        String sql = "Insert into teacher(id, name, username,password, cellno, department, designation , Email) values(?,?,?,?,?,?,?,?)";

        
        if(teacher_id.getText().equalsIgnoreCase("")||teacher_name.getText().equalsIgnoreCase("")||teacher_cell.getText().equalsIgnoreCase("")||teacher_dept.getText().equalsIgnoreCase("")||teacher_designation.getText().equalsIgnoreCase("")||teacher_mail.getText().equalsIgnoreCase("")||teacher_username.getText().equalsIgnoreCase("")||teacher_password.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "You must fill up the above boxes correcrtly");
        }
        
        else{
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management", "root", "");
            pst = (PreparedStatement) conn.prepareStatement(sql);

            pst.setInt(1, Integer.parseInt(teacher_id.getText().trim()));
            pst.setString(2, teacher_name.getText().trim());
            pst.setString(5, teacher_cell.getText().trim());
            pst.setString(6, teacher_dept.getText().trim());
            pst.setString(7, teacher_designation.getText().trim());
            pst.setString(8, teacher_mail.getText().trim());
            pst.setString(3, teacher_username.getText().trim());
            pst.setString(4, teacher_password.getText().trim());
            /*System.out.println("we are here");
             System.out.println("we are here");*/

            int v = pst.executeUpdate();
            //System.out.println(v);
            if (v == 1) {
                JOptionPane.showMessageDialog(null, "Successfully Inserted");
                retrieve();
            } else {
                JOptionPane.showMessageDialog(null, "Successfully Not Inserted");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_add_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        retrieve();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updatejButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton5ActionPerformed

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management", "root", "");

            String value1 = teacher_id.getText();
            String value2 = teacher_name.getText();
            String value3 = teacher_cell.getText();
            String value4 = teacher_dept.getText();
            String value5 = teacher_designation.getText();
            String value6 = teacher_mail.getText();
            String value7 = teacher_username.getText();
            String value8 = teacher_password.getText();

            String sql = "UPDATE teacher SET name='" + value2 + "',username='" + value7 + "',password='" + value8 + "',cellno='" + value3 + "',department='" + value4 + "',designation='" + value5 + "',Email='" + value6 + "' WHERE id='" + value1 + "'";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully Updated");
        } catch (Exception e) {
            e.printStackTrace();
        }

        retrieve();
    }//GEN-LAST:event_updatejButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        teacher_id.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        String name = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        teacher_name.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        String cellno = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        teacher_cell.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        String department = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        teacher_dept.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        String designation = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        teacher_designation.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        String email = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
        teacher_mail.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        String username = jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
        teacher_username.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        String password = jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString();
        teacher_password.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void clearjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearjButton1ActionPerformed

        teacher_id.setText("");
        teacher_name.setText("");
        teacher_cell.setText("");
        teacher_dept.setText("");
        teacher_designation.setText("");
        teacher_mail.setText("");
        teacher_username.setText("");
        teacher_password.setText("");
    }//GEN-LAST:event_clearjButton1ActionPerformed

    private void deletejButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButton4ActionPerformed
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management","root", "");
           
            
            String value1 = teacher_id.getText();
            String value2 = teacher_name.getText();
            String value3 = teacher_cell.getText();
            String value4 = teacher_dept.getText();
            String value5 = teacher_designation.getText();
            String value6 = teacher_mail.getText();
            String value7 = teacher_username.getText();
            String value8 = teacher_password.getText();

            String sql = "delete from teacher  where id ='"+value1+"'";
             pst = (PreparedStatement) conn.prepareStatement(sql);
             pst.execute();
             JOptionPane.showMessageDialog(null, "Successfully Deleted");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        retrieve();
    }//GEN-LAST:event_deletejButton4ActionPerformed

    private void signoutjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutjButton2ActionPerformed
        
        int result = JOptionPane.showConfirmDialog(null,
        "Are you sure you wish to exit application?", null, JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
        this.setVisible(false);
        Admin_info ad = new Admin_info();
        ad.setVisible(true);
        ad.setBounds(0, 0, 718, 435);
        ad.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_signoutjButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_jButton1;
    private javax.swing.JButton clearjButton1;
    private javax.swing.JButton deletejButton4;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton signoutjButton2;
    private javax.swing.JTextField teacher_cell;
    private javax.swing.JTextField teacher_dept;
    private javax.swing.JTextField teacher_designation;
    private javax.swing.JTextField teacher_id;
    private javax.swing.JTextField teacher_mail;
    private javax.swing.JTextField teacher_name;
    private javax.swing.JPasswordField teacher_password;
    private javax.swing.JTextField teacher_username;
    private javax.swing.JButton updatejButton5;
    // End of variables declaration//GEN-END:variables
}
